---
- include:              '../tasks/dependencies.yml'
- include_vars:         'escrow_user.yml'
- include_vars:         'storage_password_path.yml'
- include:              '../tasks/system_groups.yml'
- include:              '../tasks/system_users.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/symlinks.yml'
- include:              '../tasks/authorized_keys.yml'
  vars:
    authorized_keys:
      - user:           'escrow'
        keyfile:        "../../inventory/hosts/{{ member }}/users/root/files/ssh_keys/id_rsa.pub"
  with_items:           "{{ groups['escrow'] }}"
  loop_control:
    loop_var:           'member'
- include:              '../tasks/known_hosts.yml'
  vars:
    known_hosts:        "{{ groups['escrow'] }}"
- include:              '../tasks/allow_users.yml'
