---
- include_vars:         'escrow_user.yml'
- include_vars:         'storage_password_path.yml'
- include_tasks:        'tasks/common/system_groups.yml'
- include_tasks:        'tasks/common/system_users.yml'
- include_tasks:        'tasks/common/install_files.yml'
- include_tasks:        'tasks/common/template_files.yml'
- include_tasks:        'tasks/common/symlinks.yml'
- include_tasks:        'tasks/common/authorized_keys.yml'
  vars:
    authorized_keys:
      - user:           'escrow'
        keyfile:        "{{ inventory_path }}/hosts/{{ member }}/users/root/files/ssh_keys/id_rsa.pub"
  with_items:           "{{ groups['escrow'] }}"
  loop_control:
    loop_var:           'member'
- include_tasks:        'tasks/common/known_hosts.yml'
  vars:
    known_hosts:        "{{ groups['escrow'] }}"
- include_tasks:        'tasks/common/allow_users.yml'
